channels:
- conda-forge
dependencies:
- python=3.10.19
- pip<=25.3
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - defusedxml==0.7.1
  - numpy==1.26.4
  - pandas==2.1.4
  - torch==2.9.1
  - torchvision==0.24.1
  - tqdm==4.67.1
name: mlflow-env
